steps:
- name: gcr.io/kaniko-project/executor:latest
  id: image-build
  waitFor: ['-'] #parallel - dockerfile rebuilds
  args:
  - --destination=gcr.io/$PROJECT_ID/$_IMG_NAME:$SHORT_SHA
  - --cache=true
  - --cache-ttl=72h
